In [37]:
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np

In [38]:
digits = load_digits()


In [46]:
X, y = digits.data, digits.target
print((X))

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [45]:
X = StandardScaler().fit_transform(X)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train)

[[ 0.         -0.33501649 -0.46382335 ...  1.05712311  0.47246651
  -0.19600752]
 [ 0.         -0.33501649  0.79840364 ... -0.63808502 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ... -0.12952258 -0.5056698
  -0.19600752]
 ...
 [ 0.         -0.33501649  0.79840364 ...  1.56568555 -0.01660165
  -0.19600752]
 [ 0.         -0.33501649 -0.88456568 ... -1.14664746 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -0.88456568 ... -0.97712664 -0.5056698
  -0.19600752]]


In [42]:
#delta2 = (y_pred - y) * self.a2 * (1-self.a2)
y_pred = np.random.randn(X_train.shape[1], 64)
print(y_train.shape)

(1437,)
