In [10]:
from PIL import Image
import numpy as np

maze_image = Image.open('5x5.png')




In [11]:
#Converts image to a defaut tuple of RBG .convert() or greyscale .convert("L") or a Palletescale .convert("P")
# Greyscale averages the RBG tuple into a single number so its easier to work with
maze_image = maze_image.convert('P')

In [12]:
#resize image to fit scale of matrix
#Helps to convert some random scale of the image into a scale we can use
maze_image = maze_image.resize((5, 5))

In [13]:
#converts image to array

image_array = np.array(maze_image)

print(image_array)


[[1 1 0 0 2]
 [1 0 0 1 0]
 [0 0 0 1 0]
 [0 1 0 1 0]
 [3 1 0 0 0]]


In [16]:
states = 25
actions = 4
state_action_table = np.zeros((states, actions))
print(state_action_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
def create_rewards_matrix(maze):
    rewards = np.full_like(maze, -1, dtype=int)
    for y, row in enumerate(maze):
        for x, cell in enumerate(row):
            if cell == 3:  # Charging station
                rewards[y][x] = 500
            elif cell == 1:  # Wall
                rewards[y][x] = -100
            elif cell == 2:  # Charging station
                rewards[y][x] = 0
    return rewards

x = create_rewards_matrix(image_array)
print(x)

[[-100 -100   -1   -1    0]
 [-100   -1   -1 -100   -1]
 [  -1   -1   -1 -100   -1]
 [  -1 -100   -1 -100   -1]
 [ 500 -100   -1   -1   -1]]
