In [1]:
from PIL import Image
import numpy as np

maze_image = Image.open('5x5.png')




In [2]:
#Converts image to a defaut tuple of RBG .convert() or greyscale .convert("L") or a Palletescale .convert("P")
# Greyscale averages the RBG tuple into a single number so its easier to work with
maze_image = maze_image.convert('P')

In [3]:
#resize image to fit scale of matrix
#Helps to convert some random scale of the image into a scale we can use
maze_image = maze_image.resize((5, 5))

In [4]:
#converts image to array

image_array = np.array(maze_image)

print(image_array)


[[1 1 0 0 2]
 [1 0 0 1 0]
 [0 0 0 1 0]
 [0 1 0 1 0]
 [3 1 0 0 0]]


In [5]:
states = 25
actions = 4
np.zeros((states, actions))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])